name: advent-of-code-day

on:
  schedule:
    - cron: "45 5 1-25 12 *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make-day:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - run: echo "SESSION_COOKIE=${{ secrets.SESSION_COOKIE }}" >> $GITHUB_ENV

      - run: bun helpers/newDay.ts $(date +%-d)

      - run: |
          git config user.name "kie.ac"
          git config user.email "automation@kie.ac"
          git add .
          git commit -m "automation: create day $(date +%-d)"
          git push
